// src/pages/downloads/_addon.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { JavaAssetsAddon } from "./_schemas";
  import { AddonEvents, VariantEvents, VariantInfo } from "./_types";
  import Variant from "./_variant.svelte";

  export let defaultImage: string;
  export let json: JavaAssetsAddon;

  const dispatch = createEventDispatcher<AddonEvents>();

  const { name, variants } = json;

  const defaultDescription = "No description";
  const defaultVariantID = json.default;
  const pos = json.id_pos - 1;

  let currentVariantID = defaultVariantID;
  let description = defaultDescription;
  let currentImage = defaultImage;
  let url: string | undefined = undefined;

  function selectVariant(id: string): void {
    currentVariantID = id;
    dispatch("variant", { pos, variant: currentVariantID });
  }

  function updateInfo(info: VariantInfo): void {
    url = info.url;
    description = info.description ?? defaultDescription;
    currentImage = info.image ?? defaultImage;
  }

  function onVariantClick(event: CustomEvent<VariantEvents["click"]>): void {
    updateInfo(event.detail);
    selectVariant(event.detail.id);
  }

  function onVariantInfo(event: CustomEvent<VariantEvents["info"]>): void {
    if (currentVariantID === event.detail.id) {
      updateInfo(event.detail);
      selectVariant(event.detail.id);
    }
  }

  export function reset(): void {
    selectVariant("x");
  }

  export function resetDefault(): void {
    selectVariant(defaultVariantID);
  }
</script>

<div class="card card--row">
  <div class="card__image">
    <img
      class="img--pixelated"
      class:img--faded={currentImage === defaultImage}
      src={currentImage}
      alt="Addon icon"
    />
  </div>

  <div class="card__body flex flex--xsmall">
    <h5 class="card__title">{name}</h5>

    <div class="flex flex--row flex--small">
      {#each variants as variant}
        <Variant
          {currentVariantID}
          json={variant}
          on:click={onVariantClick}
          on:info={onVariantInfo}
        />
      {/each}
    </div>

    <div class="card__content">
      {description}
      {#if url !== undefined}
        (<a href={url}>GitHub</a>)
      {/if}
    </div>
  </div>
</div>

// src/pages/downloads/_components/bedrock/Addon.tsx
import { Component, createResource, Suspense } from "solid-js";
import { GitHubRepo } from "../GitHubRepo";
import { RawBaseRepo } from "../schemas";
import { RawAddon } from "./schemas";

export interface AddonProps {
  raw: RawAddon;
  base: RawBaseRepo;
}

export const Addon: Component<AddonProps> = (props) => {
  const repo = GitHubRepo.fromUrl(props.raw.url);
  const image = repo.rawContentUrl("pack_icon.png");

  const filename = props.raw.filename.replace("{version}", props.base.version);
  const url = props.base.release_url.replace("{tag}", props.base.tag).replace("{filename}", filename);

  const [description] = createResource(async () => {
    const info = await repo.fetchInfo();
    return info.description;
  });

  return (
    <div class="card card--row">
      <div class="card__image">
        <img class="img--pixelated" src={image} alt="Addon icon" />
      </div>

      <div class="card__body flex flex--xsmall">
        <h5 class="card__title">{props.raw.name}</h5>

        <div class="card__content">
          <Suspense fallback="Loading ...">{description() ?? "No description"}</Suspense> (<a href={repo.getUrl()}>GitHub</a>)
        </div>

        <a class="btn btn--primary" href={url}>
          <span class="btn-label">Download</span>

          <span class="btn-icon btn-icon--right">
            <i class="fas fa-arrow-up-right-from-square" />
          </span>
        </a>
      </div>
    </div>
  );
};
