// src/pages/downloads/_components/java/Addons.tsx
import { batch, Component, createMemo, createResource, ErrorBoundary, For, Show } from "solid-js";
import { createMutable } from "solid-js/store";
import { handleError } from "../utils";
import { Addon } from "./Addon";
import { AddonsInfo } from "./AddonsInfo";
import { AssetsSchema } from "./schemas";

const ASSETS_JSON = "https://raw.githubusercontent.com/Love-and-Tolerance/pack-dev-tools/mane/assets/java.json";

async function fetchAssetsJson(): Promise<AddonsInfo> {
  const r = await fetch(ASSETS_JSON, {
    headers: {
      Accept: "application/json",
    },
  });

  if (r.status !== 200) {
    throw new Error(`Failed to fetch assets json: ${r.status}`);
  }

  const json = await r.json();
  const raw = AssetsSchema.parse(json);

  return new AddonsInfo(raw);
}

interface InternalProps {
  info: AddonsInfo;
}

const AddonsInternal: Component<InternalProps> = (props) => {
  const selectedIds = createMutable(props.info.addons.map((addon) => addon.defaultVariant.id));

  const filename = createMemo(() => {
    return props.info.base.getFilename(selectedIds);
  });

  function getId(pos: number): string {
    return selectedIds[pos - 1] ?? "x";
  }

  function selectId(pos: number, id: string): void {
    selectedIds[pos - 1] = id;
  }

  function reset(): void {
    batch(() => {
      for (let i = 0; i < selectedIds.length; i++) {
        selectedIds[i] = "x";
      }
    });
  }

  function resetDefaults(): void {
    batch(() => {
      for (const addon of props.info.addons) {
        selectedIds[addon.idPos - 1] = addon.defaultVariant.id;
      }
    });
  }

  return (
    <>
      <h3>Minecraft versions: {props.info.base.mcVersions}</h3>

      <div class="flex flex--row flex--small">
        <button class="btn btn--primary btn--medium" type="button" onClick={reset}>
          Reset
        </button>

        <button class="btn btn--primary btn--medium" type="button" onClick={resetDefaults}>
          Select defaults
        </button>

        <a class="btn btn--primary btn--medium" href={filename()}>
          <span class="btn-label">Download</span>

          <span class="btn-icon btn-icon--right">
            <i class="fas fa-arrow-up-right-from-square" />
          </span>
        </a>
      </div>

      <div class="grid grid--col-2">
        <For each={props.info.addons}>
          {(addon) => (
            <Addon
              info={addon}
              defaultImage={props.info.base.image}
              variantId={getId(addon.idPos)}
              onVariantSelect={selectId.bind(null, addon.idPos)}
            />
          )}
        </For>
      </div>
    </>
  );
};

export const Addons: Component = () => {
  const [addons] = createResource(fetchAssetsJson);

  return (
    <>
      <h2>Custom Java downloads</h2>

      <ErrorBoundary fallback={handleError}>
        <Show when={addons()} keyed fallback={<h2>Loading...</h2>}>
          {(addons) => <AddonsInternal info={addons} />}
        </Show>
      </ErrorBoundary>
    </>
  );
};

// src/pages/downloads/_addons.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { fromZodError, ValidationError } from "zod-validation-error";
  import Addon from "./_addon.svelte";
  import { JavaAssetsAddon, JavaAssetsSchema } from "./_schemas";
  import { AddonEvents } from "./_types";
  import { parseGitHubUrl, rawContent } from "./_utils";

  let defaultImage = "";
  let releaseUrl = "";
  let mcVersion = "N/A";
  let packVersion = "N/A";
  let addonsList: Array<JavaAssetsAddon> = [];
  let ids: string[] = [];

  let error: ValidationError | undefined;

  const addonInstances: Array<Addon> = [];

  $: filename = releaseUrl.replace("{version}", packVersion).replace("{ids}", ids.join(""));

  const ASSETS_JSON = "https://raw.githubusercontent.com/Love-and-Tolerance/pack-release-builder/mane/assets/java.json";

  onMount(async () => {
    const r = await fetch(ASSETS_JSON);
    const parseResult = JavaAssetsSchema.safeParse(await r.json());

    if (!parseResult.success) {
      error = fromZodError(parseResult.error);
      return;
    }

    const repos = parseResult.data.repos;
    const base = repos.base;

    const repo = parseGitHubUrl(repos.base.url);
    defaultImage = rawContent(repo, undefined, "pack.png");

    mcVersion = base.mc_versions;
    packVersion = base.version;

    releaseUrl = base.release_url.replace("{tag}", base.tag).replace("{filename}", base.filename);

    addonsList = repos.addons;
  });

  function onVariantSelect(event: CustomEvent<AddonEvents["variant"]>): void {
    ids[event.detail.pos] = event.detail.variant;
  }

  function reset(): void {
    for (const addon of addonInstances) {
      addon.reset();
    }
  }

  function resetDefaults(): void {
    for (const addon of addonInstances) {
      addon.resetDefault();
    }
  }
</script>

<h2>Custom Java downloads</h2>

{#if error !== undefined}
  <div class="error">{error.message}</div>
{:else}
  <h3>Minecraft version: {mcVersion}</h3>

  <div class="flex flex--row flex--small">
    <button class="btn btn--primary btn--medium" type="button" on:click={reset}> Reset </button>

    <button class="btn btn--primary btn--medium" type="button" on:click={resetDefaults}> Select defaults </button>

    <a class="btn btn--primary btn--medium" href={filename}>
      <span class="btn-label">Download</span>

      <span class="btn-icon btn-icon--right">
        <i class="fas fa-arrow-up-right-from-square" />
      </span>
    </a>
  </div>

  <div class="grid grid--col-2">
    {#each addonsList as addon, index}
      <Addon {defaultImage} json={addon} on:variant={onVariantSelect} bind:this={addonInstances[index]} />
    {/each}
  </div>
{/if}
